/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Map(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/marble_run_draft.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name='Scene'>
        <group name='Circle' position={[0, 1.071, 0]}>
          <mesh
            name='Circle_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle_1.geometry}
            material={materials['Material.001']}
          />
          <mesh
            name='Circle_2'
            castShadow
            receiveShadow
            geometry={nodes.Circle_2.geometry}
            material={materials['Material.004']}
          />
        </group>
        <group name='Sketchfab_model' position={[0.812, 0.873, -0.447]} rotation={[-Math.PI / 2, 0, 0]} />

        <mesh
          name='Object_6'
          castShadow
          receiveShadow
          geometry={nodes.Object_6.geometry}
          material={materials.Material}
          position={[3.968, 3.48, 2.121]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_7'
          castShadow
          receiveShadow
          geometry={nodes.Object_7.geometry}
          material={materials.blinn12SG}
          position={[-2.57, 10.264, 1.959]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_8'
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.003']}
          position={[-2.725, 9.822, 2.076]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_9'
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.001']}
          position={[-2.83, 9.764, 3.166]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_11'
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Material.002']}
          position={[1.581, 7.033, -4.304]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_13'
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials.Material}
          position={[4.941, 5.851, -2.316]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_14'
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials.blinn22SG}
          position={[5.023, 1.307, -2.281]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_15'
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials.blinn23SG}
          position={[4.182, 8.349, -2.825]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_16'
          castShadow
          receiveShadow
          geometry={nodes.Object_16.geometry}
          material={materials.blinn24SG}
          position={[5.502, 1.714, 0.076]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_17'
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials['Material.001']}
          position={[-1.985, 6.399, 0.489]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_18'
          castShadow
          receiveShadow
          geometry={nodes.Object_18.geometry}
          material={materials['Material.002']}
          position={[-1.978, 6.003, 0.479]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_19'
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials.blinn3SG}
          position={[-3.969, 7.909, -0.236]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_20'
          castShadow
          receiveShadow
          geometry={nodes.Object_20.geometry}
          material={materials.blinn3SG}
          position={[-3.97, 7.508, -0.235]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_21'
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials.blinn6SG}
          position={[-0.726, 4.472, -2.497]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_22'
          castShadow
          receiveShadow
          geometry={nodes.Object_22.geometry}
          material={materials['Material.001']}
          position={[-1.565, 5.724, -1.223]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_23'
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials.blinn5SG}
          position={[-1.884, 4.879, 3.051]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_24'
          castShadow
          receiveShadow
          geometry={nodes.Object_24.geometry}
          material={materials.blinn6SG}
          position={[-2.236, 3.054, 1.792]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_25'
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials.blinn6SG}
          position={[-2.723, 4.319, 1.734]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_26'
          castShadow
          receiveShadow
          geometry={nodes.Object_26.geometry}
          material={materials.blinn7SG}
          position={[-3.901, 1.193, 2.663]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_27'
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials['Material.003']}
          position={[-3.901, 1.336, 2.676]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_28'
          castShadow
          receiveShadow
          geometry={nodes.Object_28.geometry}
          material={materials.blinn8SG}
          position={[1.067, 3.107, -5.206]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh
          name='Object_29'
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials.blinn8SG}
          position={[1.065, 2.706, -5.206]}
          rotation={[-Math.PI / 2, 0, 0]}
        />

        <mesh
          name='basket'
          castShadow
          receiveShadow
          geometry={nodes.basket.geometry}
          material={materials['Material.002']}
          position={[-2.873, 2.843, -3.813]}
        />
        <group name='Sketchfab_model001' position={[-2.833, 8.065, -4.214]} rotation={[-Math.PI / 2, 0, -1.368]} />
        <group name='Object_4001' position={[-2.905, 8.11, -3.793]} rotation={[-Math.PI / 2, 0, -1.368]}>
          <mesh
            name='Object_1001'
            castShadow
            receiveShadow
            geometry={nodes.Object_1001.geometry}
            material={materials['blinn1SG.001']}
          />
          <mesh
            name='Object_1001_1'
            castShadow
            receiveShadow
            geometry={nodes.Object_1001_1.geometry}
            material={materials.Mothership_Iteration1blinn3SG}
          />
          <mesh
            name='Object_1001_2'
            castShadow
            receiveShadow
            geometry={nodes.Object_1001_2.geometry}
            material={materials['blinn2SG.001']}
          />
        </group>
        <mesh
          name='stairs'
          castShadow
          receiveShadow
          geometry={nodes.stairs.geometry}
          material={materials['Material.002']}
          position={[-2.755, 7.952, -1.083]}
          rotation={[0, -0.088, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/marble_run_draft.glb')
